# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Permission Test
on: [push]
jobs:
  checkout-without-contents-permission:
    runs-on: ubuntu-latest
    permissions:
      contents: none
    steps:
      - uses: actions/checkout@v6
