# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Permission Test
on: [push]
jobs:
  checkout-without-contents-permission:
    runs-on: ubuntu-latest
    permissions:
      contents: none
    steps:
      - name: Fetch git repository
        uses: actions/checkout@v6
      - name: Check git status
        run: git status
      - name: Check git log
        run: git log
      - name: Fetch from origin
        run: git fetch origin
